language: python
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
  fast_finish: true
services:
  - docker
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coverage
  - travis_retry pip install coveralls
script:
- nosetests --with-coverage --cover-package=.
- pylint --version
- pylint brewery
- pylint dsp
- pylint measurement
- pylint testing
after_success: coveralls
notifications:
  email: false
  slack: joulia:WNFyeuBeiJJAGjU6Gwj9rPnX
deploy:
  - provider: script
    script: python register_update.py
    on:
      branch: master
      # Doesn't matter which python version. This just makes sure we deploy only
      # once.
      python: 3.6
  - provider: script
    script: "./deploy_docker.sh"
    on:
      branch: master
      # Doesn't matter which python version. This just makes sure we deploy only
      # once.
      python: 3.6
