FROM python:3.6
MAINTAINER William Schmitt (will@joulia.io)

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y python-dev
RUN apt-get install -y libmysqlclient-dev

RUN pip install -r requirements_simulation.txt

CMD python main-simulated.py
